server:
  port: 7061

spring:
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
    h2:
      console:
        path: /h2-console
        enabled: true
        settings:
          web-allow-others: true
logging:
  level:
    root: info
    com.hdfg159: debug
    org:
      springframework:
        web: debug
        security: debug